# Generated by Django 3.2.8 on 2021-12-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='catalog.Product', verbose_name='Заказанные продукты'),
        ),
    ]
