# Generated by Django 3.2.8 on 2021-12-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
