# Generated by Django 3.2.8 on 2021-12-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_attribute_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='attribute', to='catalog.Category', verbose_name='Категория'),
        ),
    ]
