# Generated by Django 3.2.8 on 2021-12-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20211221_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='attribute',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='attribute', to='catalog.Category', verbose_name='Категория'),
        ),
    ]
