# Generated by Django 3.2.8 on 2022-01-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20211221_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Vendor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='vendor',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendors',
        ),
    ]
