# Generated by Django 3.2.8 on 2022-01-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20220108_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания запроса'),
        ),
    ]
