# Generated by Django 3.2.8 on 2022-01-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20220108_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex',
        ),
    ]
